-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS orderlines;
DROP TABLE IF EXISTS bottom;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS public.user;

CREATE TABLE IF NOT EXISTS public.user
(
    id serial NOT NULL,
    username character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    role character varying(8) NOT NULL,
    balance integer,
    PRIMARY KEY (id),
    CONSTRAINT username UNIQUE (username)
    );

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    date date NOT NULL,
    status character varying(30) NOT NULL,
    user_id integer NOT NULL,
    total_price double precision NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.orderlines
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    quantity integer NOT NULL,
    topping_id integer NOT NULL,
    bottom_id integer NOT NULL,
    total_price double precision NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.topping
(
    id serial NOT NULL,
    name character varying(60) NOT NULL,
    price double precision NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.bottom
(
    id serial NOT NULL,
    name character varying(60) NOT NULL,
    price double precision NOT NULL,
    PRIMARY KEY (id)
    );

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public.user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orderlines
    ADD CONSTRAINT order_id FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orderlines
    ADD CONSTRAINT topping FOREIGN KEY (topping_id)
    REFERENCES public.topping (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orderlines
    ADD CONSTRAINT bottom FOREIGN KEY (bottom_id)
    REFERENCES public.bottom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;