@startuml
'https://plantuml.com/activity-diagram-beta


|Customer|


start
:Enters URL of Cupcake-webside in browser;
|Webside|
:Renders homepage;
:Homepage]
|Customer|
:Presses 'Login' or 'Buy Cupcakes';

repeat
    |Webside|
    :Renders Login-page;
    :Login-page]
    |Customer|
        if (Presses 'Create User' or Enters credentials) then('Create User')

            |Webside|
            :Renders Create User-page;
            :Create User-page]
            |Customer|
            :Enters username and password;
            :Indicates wether user is an admin;
            :Presses 'Create User';
            |Webside|
            :Renders Login-page;
            :Login-page]
        endif
        ->Enters credentials;
            |Customer|
            :Presses Login;
            |Webside|
            :Checks credentials;

backward: Sends msg: "(...). Try again";
-[#red]->
repeat while (Credentials?) is (Not OK)
->OK;

repeat
    :Renders Cupcake Selection-page;
    :Cupcake Selection-page]
    fork

    |Customer|
    :Chooses cupcakes;
    :Presses 'Buy';
    fork again
    |Webside|

    :Shows Cart at page;
    end fork

    |Webside|
    backward: Sends msg: "Not enough money"]

repeat while (Balance is 0 or above) is (No)
->Yes;

:Saves order;
:Creates receipt and pickup time;
:Receipt and pickup time]
fork
|Customer|
:Reads receipt and pickup time;
:Leaves webside;
:Picks up cupcakes at shop;
fork again
|Webside|
stop

|Shop|
:Asks for next order<
|Webside|
:Shows receipt of next order;

|Shop|
:Makes cupcakes;
:Cupcakes]
:Makes cupcakes ready for pickup;
:Cupcakes ready for pickup]
end fork
stop

@enduml
